const templates = [
  // Still life
  {
    name: "Block",
    type: "Still life",
    template: [
      [true, true],
      [true, true],
    ],
  },
  {
    name: "Bee-hive",
    type: "Still life",
    template: [
      [false, true, true, false],
      [true, false, false, true],
      [false, true, true, false],
    ],
  },
  {
    name: "Loaf",
    type: "Still life",
    template: [
      [false, true, true, false],
      [true, false, false, true],
      [false, true, false, true],
      [false, true, false, true],
      [false, false, true, false],
    ],
  },
  {
    name: "Boat",
    type: "Still life",
    template: [
      [true, true, false],
      [true, false, true],
      [false, true, false],
    ],
  },
  {
    name: "Tub",
    type: "Still life",
    template: [
      [false, true, false],
      [true, false, true],
      [false, true, false],
    ],
  },

  // Oscillators
  {
    name: "Blinker",
    type: "Oscillator",
    template: [
      [false, true, false],
      [false, true, false],
      [false, true, false],
    ],
  },
  {
    name: "Toad",
    type: "Oscillator",
    template: [
      [false, true, true, true],
      [true, true, true, false],
    ],
  },
  {
    name: "Beacon",
    type: "Oscillator",
    template: [
      [true, true, false, false],
      [true, false, false, false],
      [false, false, false, true],
      [false, false, true, true],
    ],
  },
  {
    name: "Beacon",
    type: "Oscillator",
    template: [
      [
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
      ],

      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],

      [
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
      ],
    ],
  },
  {
    name: "Penta-decathlon",
    type: "Oscillator",
    template: [
      [false, false, true, false, false, false, false, true, false, false],
      [true, true, false, true, true, true, true, false, true, true],
      [false, false, true, false, false, false, false, true, false, false],
    ],
  },

  // Spaceships
  {
    name: "Glider",
    type: "Spaceship",
    template: [
      [false, true, false],
      [false, false, true],
      [true, true, true],
    ],
  },
  {
    name: "Light-weight spaceship",
    type: "Spaceship",
    template: [
      [true, false, false, true, false],
      [false, false, false, false, true],
      [true, false, false, false, true],
      [false, true, true, true, true],
    ],
  },
  {
    name: "Middle-weight spaceship",
    type: "Spaceship",
    template: [
      [false, true, true, true, true, true],
      [true, false, false, false, false, true],
      [false, false, false, false, false, true],
      [true, false, false, false, true, false],
      [false, false, true, false, false, false],
    ],
  },
  {
    name: "Heavy-weight spaceship",
    type: "Spaceship",
    template: [
      [false, true, true, true, true, true, true],
      [true, false, false, false, false, false, true],
      [false, false, false, false, false, false, true],
      [true, false, false, false, false, true, false],
      [false, false, true, true, false, false, false],
    ],
  },

  // Glider gun
  {
    name: "Glider gun",
    type: "Gun",
    template: [
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
      ],
      [
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
      ],

      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
  },
];

export {
  templates,
};
